config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :cities
  resources :zones
  resources :requests
  resources :attachments

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contacts', to: 'static_pages#contacts', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contacts
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.erb
<% provide(:title, 'About Us') %>
<h1>О нас</h1>
<p>
  <a href="http://mobile-geo.ru/">ЗАО «Мобиле»</a>
  Геоинформационные системы
</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>О нас</h1>
<p>
  <a href="http://mobile-geo.ru/">ЗАО «Мобиле»</a>
  Геоинформационные системы
</p>

app/views/static_pages/contacts.erb
<% provide(:title, 'Контакты') %>
<h1>Контакты</h1>
<p>
  <a href="http://mobile-geo.ru/">ЗАО «Мобиле»</a>
  <br/>
  +7 (342) 2-362-782
</p>

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Контакты') %>
<h1>Контакты</h1>
<p>
  <a href="http://mobile-geo.ru/">ЗАО «Мобиле»</a>
  <br/>
  +7 (342) 2-362-782
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Справка</h1>
<p>

</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Заявки</h1>

  <h2>
    Начальная страница для системы заявок
  </h2>
  <% if signed_in? %>
      <h2>Здравствуйте, <%= current_user.name %></h2>
      <%= link_to "Города", cities_path %>
      <br/>
      <%= link_to "Все заявки", requests_path %>
      <br/>
      <%= link_to "Мои заявки", requests_path %>
  <% else %>
      <%= link_to "Войдите", signin_path, class: "btn btn-large btn-primary" %>
      или
      <%= link_to "Зарегистрируйтесь", signup_path, class: "btn btn-large btn-primary" %>
  <% end %>
</div>

<%= link_to image_tag("logo.jpg", alt: "ЗАО «Мобиле»"), 'http://mobile-geo.ru/' %>