config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :cities
  resources :zones
  resources :requests
  resources :attachments

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contacts', to: 'static_pages#contacts', via: 'get'

end

app/models/zone.rb
class Zone < ActiveRecord::Base
  belongs_to :city
  default_scope -> { order 'created_at DESC'}
  validates :city_id, presence: true
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :signed_in_user
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
    @city = City.find(params[:city_id])
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @city = City.find(zone_params[:city_id])
    @zone = @city.zones.build(zone_params)
    if @zone.save
      flash[:success] = "Зона города создана"
      redirect_to @city
      # format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
    else
      flash[:error] = "Не удалось создать зону города"
      redirect_to @city
      # format.html { render :new }
      # format.json { render json: @zone.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    @city = City.find(@zone.city_id)
    if @zone.update(zone_params)
      flash[:success] = "Зона сохранена"
      redirect_to @city
    else
      flash[:error] = "Изменения не сохранены"
      redirect_to @city
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    city = City.find(@zone.city_id)
    @zone.destroy
    flash[:success] = "Зона удалена"
    redirect_to city
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:zone_type, :city_id, :restriction)
    end
end

app/views/zones/_zone.html.erb
<li>
  <span class="content">
    <%= zone.zone_type %>
    <%= zone.restriction %>
    <% if signed_in? && (current_user.admin?) %>
        | <%= link_to "Редактировать", edit_zone_path(zone) %>
        | <%= link_to "Удалить", zone, method: :delete,
                      data: { confirm: "Вы уверены что хотите удалить зону?" } %>
      <% end %>
  </span>
</li>

app/views/zones/edit.html.erb
<% provide(:title, "Редактирование зоны города") %>
<h1>Редактирование зоны города</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@zone) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :zone_type, "Тип зоны" %>
        <%= f.number_field :zone_type %>

        <%= f.label :restriction, "Ограничения" %>
        <%= f.text_field :restriction %>

        <%= f.submit "Сохранить", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/zones/new.html.erb
<% provide(:title, 'Добавление зоны города') %>
<h1>Добавление зоны города <%= link_to @city.name, @city %></h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@zone) do |f| %>

        <%= f.label :zone_type, "Тип зоны" %>
        <%= f.number_field :zone_type %>

        <%= f.label :restriction, "Ограничения" %>
        <%= f.text_field :restriction %>

        <%= f.hidden_field :city_id, :value => @city.id %>

        <%= render 'shared/error_messages' %>

        <%= f.submit "Добавить зону", class: "btn btn-large btn-primary" %>
        <!--%= link_to "Добавить", { :controller => "zones", :action => "new", :city_id => @city.id }, class: "btn btn-large btn-primary" %-->
    <% end %>
  </div>
</div>