config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :cities
  resources :zones
  resources :requests
  resources :attachments

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contacts', to: 'static_pages#contacts', via: 'get'

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :zones, dependent: :destroy
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :signed_in_user
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.paginate(page: params[:page], per_page: 10)
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find(params[:id])
    @zones = @city.zones.paginate(page: params[WillPaginate], per_page: 10)
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        flash[:success] = "Город успещно добавлен"
        redirect_to cities_path
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        flash[:success] = "Город успешно обновлён"
        redirect_to @city
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      flash[:success] = 'Город удалён'
      redirect_to cities_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/views/cities/edit.html.erb
<% provide(:title, "Редактирование города") %>
<h1>Редактирование города</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@city) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name, "Название города" %>
        <%= f.text_field :name %>

        <%= f.submit "Сохранить", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/cities/index.html.erb
<% # encoding: utf-8 %>
<% provide(:title, 'Города') %>
<h1>Города</h1>

<%= will_paginate %>

<ul class="cities">
  <% @cities.each do |city| %>
      <li>
        <%= link_to city.name, city %>
        <% if signed_in? && (current_user.admin?) %>
            | <%= link_to "Редактировать", edit_city_path(city) %>
            | <%= link_to "Удалить", city, method: :delete,
                          data: { confirm: "Вы уверены что хотите удалить город " + city.name + "?" } %>
        <% end %>
      </li>
  <% end %>
  <% if signed_in? && (current_user.admin?) %>
      <%= link_to "Добавить город", new_city_path, class: "btn btn-large btn-primary" %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/cities/new.html.erb
<% # encoding: utf-8 %>
<% provide(:title, "Новый город") %>
<h1>Новый город</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@city) do |f| %>
        <%= f.label :name, "Название города" %>
        <%= f.text_field :name %>

        <%= f.submit "Добавить город", class:"btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cities/show.html.erb
<% provide(:title, @city.name) %>
<h1><%= link_to "< Другие города ", cities_path %> <%= @city.name %></h1>

<div class="span8">
  <% if @city.zones.any? %>
      <ol class="zones">
        <%= render @zones %>
      </ol>
      <%= will_paginate @zones %>
      <% if signed_in? && (current_user.admin?) %>
          <%= link_to "Добавить", { :controller => "zones", :action => "new", :city_id => @city.id }, class: "btn btn-large btn-primary" %>
      <% end %>
  <% else %>
      <h2>В город не добавлено ни одной зоны
        <% if signed_in? && (current_user.admin?) %>
            <%= link_to "Добавить", { :controller => "zones", :action => "new", :city_id => @city.id }, class: "btn btn-large btn-primary" %>
            <!--%= link_to "Добавить", new_zone_path, class: "btn btn-large btn-primary" %-->
        <% end %>
      </h2>
  <% end %>
</div>